#!/usr/bin/env bash
# Read out the message of the day
if [ -x ~/.motd ]; then
    # Execute a script
    ~/.motd
elif [ -f ~/.motd ]; then
    # Read a file
    cat ~/.motd
else
    echo "Hello, Maddy!"
fi
