#!/usr/bin/bash
# Remarkable stuff
export RMVIEW_CONF="~/.dotfiles/rmview/config.json"

# Determine which terminal emulator we're using
if [ -z "$TERM_PROGRAM" ]; then
    export TERM_PROGRAM=$(basename "/"$(ps -o cmd -f -p $(cat /proc/$(echo $$)/stat | cut -d \  -f 4) | tail -1 | sed 's/ .*$//'))
fi

# Set up editor variable
# If terminal is running in VS Code, use it as the editor
if [[ $TERM_PROGRAM = "vscode" ]]; then
    export EDITOR='code --wait'
else
    export EDITOR='nano'
fi

# Use Firefox Dev Edition as my preferred browser if it's on the path
if command -pv firefox-aurora &> /dev/null; then
    export BROWSER='firefox-aurora'
elif command -pv firefox &> /dev/null; then
    export BROWSER='firefox'
fi

# Pretty colours
export FORCE_COLOR="on"
# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
