#!/usr/bin/bash
# Remarkable stuff
export RMVIEW_CONF="~/.dotfiles/rmview/config.json"

# Determine which terminal emulator we're using
if [ -z "$TERM_PROGRAM" ]; then
    export TERM_PROGRAM=$(basename "/"$(ps -o cmd -f -p $(cat /proc/$(echo $$)/stat | cut -d \  -f 4) | tail -1 | sed 's/ .*$//'))
fi

# Set up editor variable
# If terminal is running in VS Code, use it as the editor
if [[ $TERM_PROGRAM = "vscode" ]]; then
    export EDITOR='code --wait'
else
    export EDITOR='nano'
fi

# Use Firefox Dev Edition as my preferred browser if it's on the path
if which firefox-aurora 2>&1 >/dev/null; then
    export BROWSER='firefox-aurora'
elif which firefox 2>&1 2>/dev/null; then
    export BROWSER='firefox'
fi

# Pretty colours
export FORCE_COLOR="on"
