#!/usr/bin/bash
# Set up PATH variable

export PATH=$DOTFILES/bin:$HOME/bin:/usr/local/bin:$HOME/.local/bin:$PATH

# Also add CSE bin if running on UNSW systems

if [[ $(whereami) == "cse" ]]; then
    export PATH=$DOTFILES/cse-bin:$PATH
fi
