#!/usr/bin/bash
# Set up aliases to open common GUI programs asynchronously

if command -pv dolphin &> /dev/null; then
    dolphin () {
        # FIXME: This is probably a syntax error in bash
        command -p dolphin "$@" > /dev/null 2> /dev/null &
        disown
    }
fi

if command -pv nautilus &> /dev/null; then
    nautilus() {
        command -p nautilus "$@" > /dev/null 2> /dev/null &
        disown
    }
fi

if command -pv firefox &> /dev/null; then
    firefox() {
        if which firefox-aurora &> /dev/null; then
            ff='firefox-aurora'
        else
            ff='firefox'
        fi
        command -p "$ff" "$@" > /dev/null 2> /dev/null &
        disown
    }
fi
