#!/usr/bin/bash
# Fixes for CSE systems

if [ $(whereami) == "cse" ]; then
    # Upgrading node and npm to 1531 defaults on CSE systems
    if [[ -x "~cs1531/setup/setup.sh" ]]; then
        source ~cs1531/setup/setup.sh
    fi

    # On CSE systems, we should silence the insecure directory warning
    export ZSH_DISABLE_COMPFIX="true"
fi
