#!/usr/bin/env bash
# dotup
# Update dotfiles

dotup() {
    CURR_DIR=$(pwd)
    cd $DOTFILES
    git pull

    # Eventually, I want to auto-add all new dotfiles, but currently, Tuckr
    # has some bugs with symlinking, which are not ideal. I'll wait for them to
    # be resolved before uncommenting here.
    # https://github.com/RaphGL/Tuckr/issues/85
    # tuckr add global $(whereami)

    cd $CURR_DIR
    # Two empty lines -- there is no better way to do this that also works in
    # bash
    echo
    echo
    # Now reload the config
    if [ -n "$BASH" ]; then
        source ~/.bashrc
    elif [ -n "$ZSH_NAME" ]; then
        source ~/.zshrc
    else
        echo "Not running in Bash or ZSH, no re-source of configs"
    fi
}
