#!/usr/bin/bash
# Quick command to quit the terminal
alias q="exit 0"
# And to clear the console (as well as resetting any cursor changes)
# https://superuser.com/a/123007/1709412
alias c="printf '\033\143'"
alias cls="printf '\033\143'"

# Improved ll
alias ll='ls -alF'

# Add function for combining mkdir and cd
mkcdir ()
{
    mkdir -p -- "$1" &&
    cd -P -- "$1"
}

# Add function for combining cd and ls
cdl ()
{
    cd -P -- "$1"
    ls
}

# On Linux, xdg-open does a similar thing to MacOS's open command
# Alias them to be the same
# https://superuser.com/a/38989/1709412
case "$OSTYPE" in
    # Possibly also "cygwin"
    msys*)
        alias open="start"
        ;;
    linux*)
        alias start="xdg-open"
        alias open="xdg-open"
        ;;
    darwin*)
        alias start="open"
        ;;
esac
