#!/usr/bin/bash
# VC Compiler
if command -pv java &>/dev/null && [ -f ~/Tweaks/VC.jar ] && [ -f ~/.local/bin/vcc.jar ]; then
    alias vc="java -jar ~/Tweaks/VC.jar"
    alias vcc="java -jar ~/.local/bin/vcc.jar"
fi
