# https://alacritty.org/config-alacritty.html

[window]
padding = { x = 10, y = 5 }
decorations = "None"

[font]
# Use monospace, as it is overridden elsewhere
normal = { family = "monospace" }

[cursor]
style.shape = "Beam"
style.blinking = "On"

[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
    { key = "F11", action = "ToggleFullscreen" },
]
