#!/usr/bin/env zsh
# This contains the setup for all programming languages that I use
# Conveniently, everything is managed by Mise, so I don't need to pollute my
# Path with a butt-load of nonsense
# https://mise.jdx.dev/

# Disable Gradle daemons, since they are RAM hogs which outlive most of the
# projects I open (which are just for marking)
export GRADLE_OPTS="-Dorg.gradle.daemon=false"

if command -v mise &> /dev/null; then
    if [ -n "$BASH" ]; then
        eval "$(mise activate bash)"
    elif [ -n "$ZSH_NAME" ]; then
        eval "$(mise activate zsh)"
    else
        echo "Not running in Bash or ZSH, cannot activate mise"
    fi
fi
