#!/usr/bin/env bash

file=$(realpath "$BASH_SOURCE")

user=$(ls -ld "${file}" | awk '{print $3}')

homedir="~$user"

while true; do
    read -p "Grant $user SSH access to account $(whoami)? " yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit 1;;
        * ) echo "Please answer yes or no.";;
    esac
done

# Add all keys to their authorized_keys file
for filename in "$homedir/.ssh/id_*.pub"; do
    cat filename >> $HOME/.ssh/authorized_keys
done
