#!/usr/bin/env bash
# Copies the SSH public keys for whoever owns this script into the
# authorized_keys file for whoever runs it

file=$(realpath "$BASH_SOURCE")

user=$(ls -ld "${file}" | awk '{print $3}')

while true; do
    read -p "Grant $user SSH access to account $(whoami)? " yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit 1;;
        * ) echo "Please answer yes or no.";;
    esac
done

# This won't work nicely on MacOS
files=/home/$user/.ssh/id_*.pub

# Add all keys to their authorized_keys file
for filename in $files; do
    if [[ $filename == "~$user/.ssh/id_*.pub" ]]; then
        echo "Error: no keys found"
        exit 1
    fi
    echo "Add key" $filename
    cat $filename >> $HOME/.ssh/authorized_keys
done
